import { defineConfig } from 'vite';
import vue from '@vitejs/plugin-vue';
import dts from 'vite-plugin-dts';
import path from 'node:path';

const entries = {
  index: 'src/index.ts',
  'config-provider/index': 'src/components/config-provider/index.ts',
  'button/index': 'src/components/button/index.ts',
  'icon/index': 'src/components/icon/index.ts',
  'flex/index': 'src/components/flex/index.ts',
  'input/index': 'src/components/input/index.ts',
  'checkbox/index': 'src/components/checkbox/index.ts',
  'form/index': 'src/components/form/index.ts',
  'dialog/index': 'src/components/dialog/index.ts',
  'toast/index': 'src/components/toast/index.ts',
  'card/index': 'src/components/card/index.ts',
  'watermark/index': 'src/components/watermark/index.ts',
  'picker/index': 'src/components/picker/index.ts',
  'search-bar/index': 'src/components/search-bar/index.ts',
  'virtual-list/index': 'src/components/virtual-list/index.ts',
  'notice-bar/index': 'src/components/notice-bar/index.ts',
  'swipe-cell/index': 'src/components/swipe-cell/index.ts',
  'infinite-scroll/index': 'src/components/infinite-scroll/index.ts',
  'pull-refresh/index': 'src/components/pull-refresh/index.ts',
  'back-top/index': 'src/components/back-top/index.ts',
  'scroll-area/index': 'src/components/scroll-area/index.ts',
  'affix/index': 'src/components/affix/index.ts',
  'anchor/index': 'src/components/anchor/index.ts',
  'timeline/index': 'src/components/timeline/index.ts',
  'carousel/index': 'src/components/carousel/index.ts',
  'transfer/index': 'src/components/transfer/index.ts',
  'cascader/index': 'src/components/cascader/index.ts',
  'tree-select/index': 'src/components/tree-select/index.ts',
  'tree/index': 'src/components/tree/index.ts',
  'notification/index': 'src/components/notification/index.ts',
  'calendar/index': 'src/components/calendar/index.ts',
  'autocomplete/index': 'src/components/autocomplete/index.ts',
  'segmented/index': 'src/components/segmented/index.ts',
  'safe-area/index': 'src/components/safe-area/index.ts',
  'action-sheet/index': 'src/components/action-sheet/index.ts',
  'tab-bar/index': 'src/components/tab-bar/index.ts',
  'bottom-sheet/index': 'src/components/bottom-sheet/index.ts',
  'steps/index': 'src/components/steps/index.ts',
  'descriptions/index': 'src/components/descriptions/index.ts',
  'list/index': 'src/components/list/index.ts',
  'table/index': 'src/components/table/index.ts',
  'time-picker/index': 'src/components/time-picker/index.ts',
  'date-picker/index': 'src/components/date-picker/index.ts',
  'upload/index': 'src/components/upload/index.ts',
  'rate/index': 'src/components/rate/index.ts',
  'slider/index': 'src/components/slider/index.ts',
  'input-number/index': 'src/components/input-number/index.ts',
  'accordion/index': 'src/components/accordion/index.ts',
  'dropdown/index': 'src/components/dropdown/index.ts',
  'menu/index': 'src/components/menu/index.ts',
  'breadcrumb/index': 'src/components/breadcrumb/index.ts',
  'pagination/index': 'src/components/pagination/index.ts',
  'progress/index': 'src/components/progress/index.ts',
  'image/index': 'src/components/image/index.ts',
  'avatar/index': 'src/components/avatar/index.ts',
  'tag/index': 'src/components/tag/index.ts',
  'alert/index': 'src/components/alert/index.ts',
  'empty/index': 'src/components/empty/index.ts',
  'skeleton/index': 'src/components/skeleton/index.ts',
  'spinner/index': 'src/components/spinner/index.ts',
  'badge/index': 'src/components/badge/index.ts',
  'tabs/index': 'src/components/tabs/index.ts',
  'tooltip/index': 'src/components/tooltip/index.ts',
  'popover/index': 'src/components/popover/index.ts',
  'drawer/index': 'src/components/drawer/index.ts',
  'select/index': 'src/components/select/index.ts',
  'switch/index': 'src/components/switch/index.ts',
  'radio/index': 'src/components/radio/index.ts',
  'textarea/index': 'src/components/textarea/index.ts',
  'divider/index': 'src/components/divider/index.ts',
  'space/index': 'src/components/space/index.ts',
  'grid/index': 'src/components/grid/index.ts',
  'typography/index': 'src/components/typography/index.ts',
};

export default defineConfig({
  plugins: [
    vue(),
    dts({
      entryRoot: 'src',
      outDir: 'dist',
      tsconfigPath: path.resolve(import.meta.dirname, 'tsconfig.json'),
      exclude: ['**/*.test.ts'],
    }),
  ],
  resolve: {
    alias: {
      '@xiaoli-ui/internal-core': path.resolve(import.meta.dirname, '../internal-core/src/index.ts'),
      '@xiaoli-ui/internal-dom': path.resolve(import.meta.dirname, '../internal-dom/src/index.ts'),
    },
  },
  build: {
    sourcemap: true,
    lib: {
      entry: entries,
      formats: ['es'],
    },
    rollupOptions: {
      external: ['vue', '@xiaoli-ui/theme', '@xiaoli-ui/tokens'],
    },
  },
});
